graasp/graasp-desktop

public/app/listeners/getSpaces.js
public/app/listeners/index.js
public/electron.js

Factor out the getSpaces listener to its own file.
refs #104

refactor: factor out getSpaces listener

---

public/app/listeners/exportSpace.js
public/app/listeners/index.js
public/electron.js

Factor out the exportSpace listener to its own file.
refs #104

refactor: factor out exportSpace listener

---

src/components/space/SpaceNotFound.js

fix: implement translate function correctly

---

public/app/config/config.js
public/electron.js

fix: resolve path for app.getPath for Windows

---

public/electron.js

refactor: adapt menu for ios users

---

public/app/listeners/getLanguage.js
public/app/listeners/index.js
public/electron.js

Factor out the getLanguage listener to its own file.
refs #104

refactor: factor out getLanguage listener

---

public/app/listeners/index.js
public/app/listeners/setLanguage.js
public/electron.js

Factor out the setLanguage listener to its own file.
refs #104

refactor: factor out setLanguage listener

---

package.json

chore: add kim as a contributor

---

public/app/config/mapping.js

Added the mappings for the Twente online to offline apps.

feat: update mapping.js to include twente apps

---

public/electron.js

fix: pass database in setLanguage argument

---

src/App.js
src/__snapshots__/App.test.js.snap
src/index.js

fix: display connexion status toastr only on change

---

src/utils/search.js

refactor: include description when searching for a space

---

src/components/common/MainMenu.js
src/components/common/MainMenu.test.js
src/components/common/__snapshots__/MainMenu.test.js.snap

feat: close app from mainmenu

---

src/components/common/MainMenu.js

refactor: change classroom icon in mainmenu

---

src/components/classrooms/ActionIcon.js
src/components/classrooms/ClassroomLegend.js
src/components/classrooms/ClassroomScreen.js
src/components/classrooms/EditUserInClassroomButton.js
src/components/classrooms/ResourceIcon.js
src/components/classrooms/StudentsTable.js

refactor: add classroom legend, refactor resource and action icons

---

src/components/dashboard/ActionEditor.js
src/components/dashboard/Dashboard.js
src/config/constants.js
src/langs/en.json
src/langs/fr.json

feat: add user filter in dashboard

---

public/app/listeners/addClassroom.js

fix: do not add classroom when name already exists

---

src/components/Settings.js
src/components/__snapshots__/Settings.test.js.snap
src/config/selectors.js
test/settings.test.js
test/spaces/loadSpace.test.js

fix: fix minor test issues

---

src/components/phase/PhaseApp.js

fix: does not save action and resource when space is not saved

---

src/components/SpacesNearby.js

fix(spaces nearby): get correctly geolocation from user

---

src/components/dashboard/ActionPieChart.js
src/config/constants.js

refactor: update accent colors

---

src/components/signin/SignInScreen.js

fix: fix saving login action twice on signin

---

src/components/space/SyncVisualScreen.js

fix(sync): add default protocol for remote space image

---

README.md

docs: update readme with deployement steps

---

src/components/dashboard/ActionBarChart.js
src/components/dashboard/ActionLineChart.js
src/components/dashboard/ActionPieChart.js
src/components/dashboard/ActionTotalCount.js
src/components/dashboard/Dashboard.js
src/components/dashboard/Dashboard.test.js
src/components/dashboard/__snapshots__/Dashboard.test.js.snap
src/config/selectors.js

fix(dashboard): add fallback data, add tests

---

src/actions/layout.js
src/components/common/Main.js
src/reducers/layout.js
src/types/layout.js

keeps drawer state
closes #277

feat: keep drawer state

---

public/app/listeners/deleteUsersInClassroom.js

fix: delete related resources when deleting user in classroom

---

src/components/phase/PhaseItem.js
src/components/phase/PhasePdf.js
src/config/constants.js

You can test this branch with my space `6006d3f3885aee668f47694c`
close #363

feat: display pdf files

---

src/components/phase/PhasePdf.js

close #366 
For some reason it was not in full width/height anymore.. I took this opportunity to refactor the whole styles of this component

refactor: use classes for PhasePdf

---

src/components/phase/PhaseImage.css
src/components/phase/PhaseVideo.css

style: do not stretch images and vidoes in full width
